[build]
  publish = "docs/.vitepress/dist"    # путь к собранным файлам
  command = "npm run build"           # ваша команда для сборки

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200